site_name: "LearningDITA 中文版"
main_site_name: 技术传播百态说
main_site_url: https://www.tcblabber.cn/
theme:
  name: material
  language: zh
  logo: assets/logo/logo_v3.svg
  favicon: assets/logo/favicon.ico
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
  custom_dir: overrides

extra_css:
  - assets/stylesheets/palette.css
  - assets/stylesheets/page.css
  - assets/stylesheets/nav.css
  - assets/stylesheets/header.css
  - assets/stylesheets/footer.css
  - assets/stylesheets/codeblock.css

extra:
  homepage: https://www.tcblabber.cn/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wongyah/LearningDITA
      name: "LearningDITA中文版的GitHub存储库"
    - icon: simple/wechat
      link: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"
      name: "微信公众号@技术传播百态说"
    - icon: simple/zhihu
      link: "https://www.zhihu.com/column/c_1548252009672929280"
      name: "知乎专栏@技术传播百态说"
    - icon: material/email
      link: "mailto:wongyah@126.com?subject=Markdown%20Syntax%20Hub"
      name: "我的邮箱"

copyright: "&copy; 2025 王烨."

nav:
  - 版权声明: notice.md
  - DITA 概述:
    - DITA 简介:
      - course01-intro/dita_intro/index.md
      - course01-intro/dita_intro/lc_dita.md
      - course01-intro/dita_intro/lc_markup.md
      - course01-intro/dita_intro/lc_structure.md
      - course01-intro/dita_intro/lc_topic.md
    - 主题类型:
      - course01-intro/infotypes/index.md
      - course01-intro/infotypes/lc_topictypes.md
      - course01-intro/infotypes/lc_generic_topic.md
      - course01-intro/infotypes/lc_concept.md
      - course01-intro/infotypes/lc_task.md
      - course01-intro/infotypes/lc_reference.md
      - course01-intro/infotypes/lc_gloss.md
      - course01-intro/infotypes/lc_specialization.md
    - 元数据:
      - course01-intro/metadata/index.md
      - course01-intro/metadata/lc_md_definition.md
      - course01-intro/metadata/lc_md_use.md
    - 创建 DITA 内容:
      - course01-intro/authoring/index.md
      - course01-intro/authoring/lc_create_topic.md
      - course01-intro/authoring/lc_create_topic_oxygen.md
      - course01-intro/authoring/lc_notes.md
      - course01-intro/authoring/lc_lists.md
      - course01-intro/authoring/lc_inline.md
    - 表格:
      - course01-intro/tables/index.md
      - course01-intro/tables/lc_tables.md
      - course01-intro/tables/lc_table_simple.md
      - course01-intro/tables/lc_table_cals.md
      - 最佳实践: course01-intro/tables/lc_best_practices.md
    - 链接:
      - course01-intro/links/index.md
      - course01-intro/links/lc_links.md
      - course01-intro/links/lc_maps.md
      - course01-intro/links/lc_transforming.md
      - course01-intro/links/lc_xrefs.md
      - course01-intro/links/lc_related_links.md
      - course01-intro/links/lc_relationships.md
  - 创建概念型主题:
    - 概念型主题简介:
      - course02-authoring_concepts/concept_intro/index.md
      - course02-authoring_concepts/concept_intro/lc_example_files.md
      - course02-authoring_concepts/concept_intro/lc_creating_new.md
      - course02-authoring_concepts/concept_intro/lc_basic_elements.md
      - course02-authoring_concepts/concept_intro/sa_new_concept.md
    - 图片和表格:
      - course02-authoring_concepts/images_and_tables/index.md
      - course02-authoring_concepts/images_and_tables/lc_images.md
      - course02-authoring_concepts/images_and_tables/lc_simpletables.md
      - course02-authoring_concepts/images_and_tables/lc_tables.md
      - course02-authoring_concepts/images_and_tables/sa_concept_images_tables.md
    - 更多元素:
      - course02-authoring_concepts/more_elements/index.md
      - course02-authoring_concepts/more_elements/lc_inline.md
      - course02-authoring_concepts/more_elements/lc_elements.md
      - course02-authoring_concepts/more_elements/sa_concept_elements.md
    - 高级元素:
      - course02-authoring_concepts/advanced/index.md
      - course02-authoring_concepts/advanced/lc_advanced.md
      - course02-authoring_concepts/advanced/lc_more_advanced.md
      - course02-authoring_concepts/advanced/sa_concept_advanced.md
    - 最佳实践:
      - course02-authoring_concepts/best_practices/index.md
      - course02-authoring_concepts/best_practices/lc_formatting.md
      - course02-authoring_concepts/best_practices/lc_consistency.md
      - course02-authoring_concepts/best_practices/lc_semantic.md
  - 创建任务型主题:
    - 任务型主题简介:
      - course03-authoring_tasks/task_intro/index.md
      - course03-authoring_tasks/task_intro/lc_example_files.md
      - course03-authoring_tasks/task_intro/lc_strict_general.md
      - course03-authoring_tasks/task_intro/lc_creating_new.md
      - course03-authoring_tasks/task_intro/lc_optional_elements.md
      - course03-authoring_tasks/task_intro/sa_new_task.md
    - 插入操作流程:
      - course03-authoring_tasks/steps/index.md
      - course03-authoring_tasks/steps/lc_steps_w_task.md
      - course03-authoring_tasks/steps/lc_choices.md
      - course03-authoring_tasks/steps/lc_choicetable.md
      - course03-authoring_tasks/steps/lc_substep.md
      - course03-authoring_tasks/steps/lc_stepresults.md
      - course03-authoring_tasks/steps/lc_stepsection.md
      - course03-authoring_tasks/steps/sa_task_steps.md
    - 插入收尾性元素:
      - course03-authoring_tasks/finishing/index.md
      - course03-authoring_tasks/finishing/lc_results.md
      - course03-authoring_tasks/finishing/lc_example.md
      - course03-authoring_tasks/finishing/lc_whatsnext.md
      - course03-authoring_tasks/finishing/sa_task_finishing.md
    - 最佳实践:
      - course03-authoring_tasks/best_practices/index.md
      - course03-authoring_tasks/best_practices/lc_bp_planning.md
      - course03-authoring_tasks/best_practices/lc_bp_context.md
      - course03-authoring_tasks/best_practices/lc_bp_short.md
      - course03-authoring_tasks/best_practices/lc_bp_substeps.md
      - course03-authoring_tasks/best_practices/lc_bp_reuse.md
  - 创建参考型主题:
    - 参考型主题简介:
      - course04-authoring_reference/reference/index.md
      - course04-authoring_reference/reference/lc_example_files.md
      - course04-authoring_reference/reference/lc_about_ref.md
      - course04-authoring_reference/reference/lc_creating_new_ref.md
      - course04-authoring_reference/reference/lc_adding_refsyn.md
      - course04-authoring_reference/reference/lc_adding_properties.md
      - course04-authoring_reference/reference/sa_reference.md
    - 最佳实践:
      - course04-authoring_reference/best_practices/index.md
      - course04-authoring_reference/best_practices/lc_bp_template.md
      - course04-authoring_reference/best_practices/lc_bp_linking.md
      - course04-authoring_reference/best_practices/lc_pr-d.md
  - 创建术语主题:
    - 创建术语词条主题:
      - course05-authoring_gloss/glossary/index.md
      - course05-authoring_gloss/glossary/lc_example_files.md
      - course05-authoring_gloss/glossary/lc_about_glossentry.md
      - course05-authoring_gloss/glossary/lc_new_glossentry.md
      - course05-authoring_gloss/glossary/lc_glossary_map.md
      - course05-authoring_gloss/glossary/sa_glossentry.md
    - 创建术语分组主题:
      - course05-authoring_gloss/glossgroup/index.md
      - course05-authoring_gloss/glossgroup/lc_about_glossgroup.md
      - course05-authoring_gloss/glossgroup/lc_new_glossgroup.md
      - course05-authoring_gloss/glossgroup/sa_glossgroup.md
    - 最佳实践:
      - course05-authoring_gloss/best_practice/index.md
      - course05-authoring_gloss/best_practice/lc_bp_naming.md
      - course05-authoring_gloss/best_practice/lc_bp_good_glossentry.md
      - course05-authoring_gloss/best_practice/lc_bp_glossarylist.md
      - course05-authoring_gloss/best_practice/lc_bp_control_glossaries.md
  - 创建导图:
    - 创建 DITA 导图:
      - course06-creating_maps_bookmaps/maps/index.md
      - course06-creating_maps_bookmaps/maps/lc_example_files.md
      - course06-creating_maps_bookmaps/maps/lc_map_new.md
      - course06-creating_maps_bookmaps/maps/lc_map_adding_topicrefs.md
      - course06-creating_maps_bookmaps/maps/lc_map_adding_maprefs.md
      - course06-creating_maps_bookmaps/maps/sa_maps.md


markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      base_path: snippets

